/**
 * A single video asset with all format/size variants.
 * - mp4:    h264 full-res — universal fallback
 * - webm:   vp9 full-res — better compression (generated by scripts/optimize-videos.mjs)
 * - poster: first-frame JPEG @1280×720 (generated by scripts/optimize-videos.mjs)
 * - mobile: h264 ≤720px wide (generated by scripts/optimize-videos.mjs)
 */
export interface VideoEntry {
  mp4: string
  webm: string
  poster: string
  mobile: string
}

const CF = 'https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P'

export const VIDEOS = {
  heroLoop: {
    mp4: `${CF}/hf_20260405_074625_a81f018a-956b-43fb-9aee-4d1508e30e6a.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  /** Tierra Singular — drone over estancia domes at dawn.
   *  Placeholder: media-optimizer will replace with final URL. */
  propertyFeature: {
    mp4: `${CF}/hf_20260402_054547_9875cfc5-155a-4229-8ec8-b7ba7125cbf8.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  featured: {
    mp4: `${CF}/hf_20260402_054547_9875cfc5-155a-4229-8ec8-b7ba7125cbf8.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  philosophy: {
    mp4: `${CF}/hf_20260307_083826_e938b29f-a43a-41ec-a153-3d4730578ab8.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  serviceStrategy: {
    mp4: `${CF}/hf_20260314_131748_f2ca2a28-fed7-44c8-b9a9-bd9acdd5ec31.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  serviceCraft: {
    mp4: `${CF}/hf_20260324_151826_c7218672-6e92-402c-9e45-f1e0f454bdc4.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  aetheraCinematic: {
    mp4: `${CF}/hf_20260328_083109_283f3553-e28f-428b-a723-d639c617eb2b.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
  vexVentures: {
    mp4: `${CF}/hf_20260403_050628_c4e32401-fab4-4a27-b7a8-6e9291cd5959.mp4`,
    webm: '',
    poster: '',
    mobile: '',
  },
} satisfies Record<string, VideoEntry>
